on:
  push:
    branch: main
name: Deploy to Deuxfleurs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm install -g dxfl
      - run: npx --yes dxfl deploy signatures.gaite-lyrique.net public/ --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEUXFLEURS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEUXFLEURS_SECRET }}
